---
title: C28105 | Microsoft-Dokumentation
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 836a1571190a79579c47774e4dfd9c0aa0b508c7
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 08/22/2018
ms.locfileid: "47513211"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Die neueste Version dieses Themas finden Sie unter [C28105](https://docs.microsoft.com/visualstudio/code-quality/c28105).  
  
Warnung C28105: Verlust von Ressource aufgrund einer Ausnahme  
  
 Die angegebene Ressource ist nicht freigegeben werden, wenn eine Ausnahme ausgelöst wird. Die Anweisung, die vom Pfad angegebenen kann es sich um eine Ausnahme ausgelöst. Diese Warnung ist ähnlich wie in "Warnung" [C28103](../code-quality/c28103.md), außer dass in diesem Fall eine Ausnahme beteiligt ist.  
  
## <a name="example"></a>Beispiel  
 Im folgenden Codebeispiel wird diese Warnung generiert:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Im folgenden Codebeispiel wird diese Warnung vermieden:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```



